### ISSUE TITLE
Invalid certificate?

### ISSUE THREAD

**Issue by gbraad** [unhosted/store#3]
When opening https://unhosted-store.5apps.com/ the browser redirects to https://apps.unhosted.org/, then a popup about invalid certificate appears.

**Comment by raucao** [comment]
Yes, @michielbdejong needs to add a CNAME entry to validate the new one. Not sure what the cause of the delay in adding it is. Maybe on vacation or something.

**Comment by gbraad** [comment]
I am pretty sure @michielbdejong is easing into his new job

**Comment by michielbdejong** [comment]
CNAME added, sorry for the delay, I was indeed busy at my new job! :)

**Comment by gbraad** [comment]
Well, the banner does not show now... but the certificate did expire on 2nd of August, 2015.

![screen shot 2015-08-10 at 3 47 56 pm](https://cloud.githubusercontent.com/assets/1894/9162190/4fbc525e-3f77-11e5-8d1c-cd1ebb5c6d88.png)

**Comment by raucao** [comment]
New cert is deployed. Some browsers might use a cached version of the old one for a bit longer.
